#----------------------------------------------------------------------------
#       Make Workspace
#
# $Id: MakeWorkspaceCreator.pm 2035 2011-10-06 15:05:21Z johnnyw $
#
# This file was generated by MPC.  Any changes made directly to
# this file will be lost the next time it is generated.
#
# MPC Command:
# /home/hilljh/MPC/mwc.pl -type make /home/hilljh/cs363-sandbox/assignment2-lifeline/jascho/cs36300-fall2018-composition
#
#----------------------------------------------------------------------------


all: assignment2

clean depend generated realclean check-syntax $(CUSTOM_TARGETS):
	@$(MAKE) -f Makefile.assignment2 $(@)

.PHONY: assignment2
assignment2:
	@$(MAKE) -f Makefile.assignment2 all

project_name_list:
	@echo assignment2
